# Generated by Django 4.1.2 on 2022-11-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTW',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('cancelled', 'cancelled'), ('authorized', 'authorized'), ('suspended', 'suspended'), ('closed', 'closed')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField()),
                ('authorized_at', models.DateTimeField()),
                ('suspended_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('planned_work_at', models.DateTimeField()),
                ('work_description', models.CharField(max_length=64)),
                ('work_type', models.CharField(max_length=64)),
                ('work_location', models.CharField(max_length=64)),
                ('performing_authority', models.CharField(max_length=64)),
                ('approved_by', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=64)),
                ('cancelled_by', models.CharField(max_length=64)),
                ('authorized_by', models.CharField(max_length=64)),
                ('suspended_by', models.CharField(max_length=64)),
                ('closed_by', models.CharField(max_length=64)),
            ],
        ),
    ]
