# Generated by Django 4.1.2 on 2022-11-06 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptw',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='suspended_at',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='suspended_by',
        ),
        migrations.RemoveField(
            model_name='ptw',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ptw',
            name='prefix',
            field=models.CharField(choices=[('PTW', 'PTW'), ('HVPTW', 'HVPTW'), ('HVSFT', 'HVSFT')], default='PTW', max_length=5),
        ),
        migrations.AlterField(
            model_name='ptw',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ptw',
            name='work_description',
            field=models.CharField(default='TBC', max_length=64),
        ),
        migrations.AlterField(
            model_name='ptw',
            name='work_location',
            field=models.CharField(default='TBC', max_length=64),
        ),
    ]
