# Generated by Django 4.1.2 on 2022-11-10 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0003_inhibit_isolation_safeentry_alter_ptw_authorized_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhibit',
            name='authorized_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='block_or_suppress',
            field=models.CharField(choices=[('block', 'block'), ('suppress', 'suppress')], default='block', max_length=10),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='ias_tags',
            field=models.CharField(default='TBC', max_length=60),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='location',
            field=models.CharField(default='TBC', max_length=60),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='performing_authority',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='related_tags',
            field=models.CharField(default='TBC', max_length=60),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('authorized', 'authorized'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='system_description',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='system_maximo_tag',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='inhibit',
            name='work_description',
            field=models.CharField(default='TBC', max_length=60),
        ),
        migrations.AddField(
            model_name='isolation',
            name='authorized_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='isolation',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='isolation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='isolation',
            name='equipment_description',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='isolation',
            name='equipment_maximo_tag',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='isolation',
            name='performing_authority',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='isolation',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('authorized', 'authorized'), ('long term', 'long term'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='authorized_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='performing_authority',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='space_description',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='space_maximo_tag',
            field=models.CharField(default='TBC', max_length=24),
        ),
        migrations.AddField(
            model_name='safeentry',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('authorized', 'authorized'), ('closed', 'closed'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='inhibit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='isolation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ptw',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('authorized', 'authorized'), ('suspended', 'suspended'), ('closed', 'closed'), ('cancelled', 'cancelled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='safeentry',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
