# Generated by Django 4.1.2 on 2022-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0004_inhibit_authorized_at_inhibit_block_or_suppress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolation',
            name='isolation_type',
            field=models.CharField(choices=[('electrical', 'electrical'), ('mechanical', 'mechanical'), ('electrical & mechanical', 'electrical & mechanical')], default='electrical', max_length=24),
        ),
    ]
