# Generated by Django 4.1.2 on 2022-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0005_isolation_isolation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('restriction_details', models.CharField(max_length=100)),
                ('is_self_restriction', models.BooleanField()),
            ],
        ),
    ]
