# Generated by Django 4.1.2 on 2022-11-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0012_alter_ptw_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simops',
            name='restriction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptw.restriction'),
        ),
    ]
