# Generated by Django 4.1.2 on 2022-11-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0014_alter_simops_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptw',
            name='ref_inhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ptw.inhibit'),
        ),
        migrations.AddField(
            model_name='ptw',
            name='ref_isolation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ptw.isolation'),
        ),
        migrations.AddField(
            model_name='ptw',
            name='ref_safe_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ptw.safeentry'),
        ),
        migrations.AlterField(
            model_name='ptw',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Basket Transfers', 'Basket Transfers'), ('Bunkering Fuel and Base Oil', 'Bunkering Fuel and Base Oil'), ('Confined Space Entry', 'Confined Space Entry'), ('Crane Operations', 'Crane Operations'), ('Drilling', 'Drilling'), ('Managed Pressure Drilling', 'Managed Pressure Drilling'), ('Explosive Handling', 'Explosive Handling'), ('Helicopter Operations', 'Helicopter Operations'), ('Hot Work', 'Hot Work'), ('Man Riding Derrick', 'Man Riding Derrick'), ('Man Riding Moonpool', 'Man Riding Moonpool'), ('Pressure Testing', 'Pressure Testing'), ('Radioactive Handling', 'Radioactive Handling'), ('Supply Boat Operations', 'Supply Boat Operations'), ('Well Testing', 'Well Testing'), ('Wireline', 'Wireline'), ('Overside Work', 'Overside Work'), ('Running Marine Riser', 'Running Marine Riser'), ('ROV Operations', 'ROV Operations'), ('Riserless Drilling', 'Riserless Drilling'), ('Critical Ballast', 'Critical Ballast'), ('Methanol', 'Methanol'), ('Safety System', 'Safety System')], max_length=64),
        ),
        migrations.AlterField(
            model_name='simops',
            name='work_type_1',
            field=models.CharField(blank=True, choices=[('Basket Transfers', 'Basket Transfers'), ('Bunkering Fuel and Base Oil', 'Bunkering Fuel and Base Oil'), ('Confined Space Entry', 'Confined Space Entry'), ('Crane Operations', 'Crane Operations'), ('Drilling', 'Drilling'), ('Managed Pressure Drilling', 'Managed Pressure Drilling'), ('Explosive Handling', 'Explosive Handling'), ('Helicopter Operations', 'Helicopter Operations'), ('Hot Work', 'Hot Work'), ('Man Riding Derrick', 'Man Riding Derrick'), ('Man Riding Moonpool', 'Man Riding Moonpool'), ('Pressure Testing', 'Pressure Testing'), ('Radioactive Handling', 'Radioactive Handling'), ('Supply Boat Operations', 'Supply Boat Operations'), ('Well Testing', 'Well Testing'), ('Wireline', 'Wireline'), ('Overside Work', 'Overside Work'), ('Running Marine Riser', 'Running Marine Riser'), ('ROV Operations', 'ROV Operations'), ('Riserless Drilling', 'Riserless Drilling'), ('Critical Ballast', 'Critical Ballast'), ('Methanol', 'Methanol'), ('Safety System', 'Safety System')], max_length=64),
        ),
        migrations.AlterField(
            model_name='simops',
            name='work_type_2',
            field=models.CharField(blank=True, choices=[('Basket Transfers', 'Basket Transfers'), ('Bunkering Fuel and Base Oil', 'Bunkering Fuel and Base Oil'), ('Confined Space Entry', 'Confined Space Entry'), ('Crane Operations', 'Crane Operations'), ('Drilling', 'Drilling'), ('Managed Pressure Drilling', 'Managed Pressure Drilling'), ('Explosive Handling', 'Explosive Handling'), ('Helicopter Operations', 'Helicopter Operations'), ('Hot Work', 'Hot Work'), ('Man Riding Derrick', 'Man Riding Derrick'), ('Man Riding Moonpool', 'Man Riding Moonpool'), ('Pressure Testing', 'Pressure Testing'), ('Radioactive Handling', 'Radioactive Handling'), ('Supply Boat Operations', 'Supply Boat Operations'), ('Well Testing', 'Well Testing'), ('Wireline', 'Wireline'), ('Overside Work', 'Overside Work'), ('Running Marine Riser', 'Running Marine Riser'), ('ROV Operations', 'ROV Operations'), ('Riserless Drilling', 'Riserless Drilling'), ('Critical Ballast', 'Critical Ballast'), ('Methanol', 'Methanol'), ('Safety System', 'Safety System')], max_length=64),
        ),
    ]
