# Generated by Django 4.1.2 on 2023-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0015_ptw_ref_inhibit_ptw_ref_isolation_ptw_ref_safe_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
