# Generated by Django 4.1.2 on 2023-01-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0016_alter_isolation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhibit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ptw',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='safeentry',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
