# Generated by Django 4.1.2 on 2024-01-12 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0017_alter_inhibit_created_at_alter_ptw_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Abandon', 'Abandon'), ('Supervisor Missing', 'Supervisor Missing'), ('Lifeboat Launch', 'Lifeboat Launch'), ('Fire Internal', 'Fire Internal'), ('Fire External', 'Fire External'), ('Fire Machinery', 'Fire Machinery'), ('Fire Accommodation', 'Fire Accommodation'), ('Fire Galley', 'Fire Galley'), ('Liferaft', 'Liferaft'), ('Liferaft Davit & Inflation', 'Liferaft Davit & Inflation'), ('Alternate ECC', 'Alternate ECC'), ('Line Throwing', 'Line Throwing'), ('Ballast Control', 'Ballast Control'), ('Collision', 'Collision'), ('Heavy WX', 'Heavy WX'), ('Structural', 'Structural'), ('Grounding', 'Grounding'), ('DP Drill', 'DP Drill'), ('Blackout', 'Blackout'), ('Emergency Steering', 'Emergency Steering'), ('Gas H2S', 'Gas H2S'), ('Helideck Emergency', 'Helideck Emergency'), ('Rescue at Height', 'Rescue at Height'), ('MOB', 'MOB'), ('SOPEP', 'SOPEP'), ('Confined Space', 'Confined Space'), ('First Aid', 'First Aid'), ('ISPS', 'ISPS'), ('Well Control', 'Well Control')], max_length=32)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_next', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='Drill description:', max_length=512)),
            ],
        ),
    ]
