# Generated by Django 4.1.2 on 2024-01-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0018_drill'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='sub_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Machinery', 'Machinery'), ('Accommodation', 'Accommodation'), ('Galley', 'Galley')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='drill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drill',
            name='type',
            field=models.CharField(choices=[('Abandon', 'Abandon'), ('Supervisor Missing', 'Supervisor Missing'), ('Lifeboat Launch', 'Lifeboat Launch'), ('Fire', 'Fire'), ('Liferaft', 'Liferaft'), ('Liferaft Davit & Inflation', 'Liferaft Davit & Inflation'), ('Alternate ECC', 'Alternate ECC'), ('Line Throwing', 'Line Throwing'), ('Ballast Control', 'Ballast Control'), ('Collision', 'Collision'), ('Heavy WX', 'Heavy WX'), ('Structural', 'Structural'), ('Grounding', 'Grounding'), ('DP Drill', 'DP Drill'), ('Blackout', 'Blackout'), ('Emergency Steering', 'Emergency Steering'), ('Gas H2S', 'Gas H2S'), ('Helideck Emergency', 'Helideck Emergency'), ('Rescue at Height', 'Rescue at Height'), ('MOB', 'MOB'), ('SOPEP', 'SOPEP'), ('Confined Space', 'Confined Space'), ('First Aid', 'First Aid'), ('ISPS', 'ISPS'), ('Well Control', 'Well Control')], max_length=32),
        ),
    ]
