# Generated by Django 4.1.2 on 2024-01-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0019_drill_sub_type_alter_drill_id_alter_drill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='sub_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Machinery', 'Machinery'), ('Accommodation', 'Accommodation'), ('Galley', 'Galley')], default=None, max_length=32, null=True),
        ),
    ]
