# Generated by Django 4.1.2 on 2024-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0020_alter_drill_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='sub_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Machinery', 'Machinery'), ('Accommodation', 'Accommodation'), ('Galley', 'Galley')], default='Internal', max_length=32),
            preserve_default=False,
        ),
    ]
