# Generated by Django 4.1.2 on 2024-01-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0024_alter_drill_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='long_description',
            field=models.CharField(default='Long description:', max_length=1024),
        ),
        migrations.AddField(
            model_name='drill',
            name='personnel',
            field=models.CharField(default='Personnel:', max_length=1024),
        ),
        migrations.AlterField(
            model_name='drill',
            name='description',
            field=models.CharField(default='Drill description:', max_length=128),
        ),
    ]
