# Generated by Django 4.1.2 on 2024-10-04 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0026_drilltype_alter_drill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ptw',
            name='work_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ptw.location'),
        ),
    ]
